[package]
authors = ["Daniel Vogelbacher <daniel@chaospixel.com>", "Pedro Côrte-Real <pedro@pedrocr.net>"]
categories = ["multimedia::images"]
edition = "2018"
license = "LGPL-2.1"
name = "rawler"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "data/cameras/join.rs"


[features]
# This is a developer feature, it enabled deep inspection of algorithm execution stages
inspector = []
samplecheck = []

[dependencies]
bitstream-io = "1.1.0"
byteorder = "1.4.3"
enumn = "0.1.3"
hex = "0.4.3"
image = "0.23.14"
itertools = "0.10.1"
lazy_static = "1.4.0"
libc = "0.2.97"
libflate = "1.1.0"
log = "0.4.14"
md5 = "0.7.0"
rayon = "1.5.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.25"
toml = "0.5.8"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.51"
futures = "0.3.15"

[dev-dependencies]
serde_yaml = "0.8.17"
env_logger = "0.8.4"

[build-dependencies]
glob = "0.3.0"
toml = "0.5.8"
rustc_version = "0.4.0"

